# Generated by Django 6.0.1 on 2026-02-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 14, 13, 12, 39, 290528, tzinfo=datetime.timezone.utc)),
        ),
    ]
