# Generated by Django 6.0.1 on 2026-03-07 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamegenre_alter_game_date_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 7, 13, 5, 21, 233343, tzinfo=datetime.timezone.utc)),
        ),
    ]
