# Generated by Django 6.0.1 on 2026-03-07 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 7, 13, 6, 59, 275825, tzinfo=datetime.timezone.utc)),
        ),
    ]
