# Generated by Django 6.0.1 on 2026-03-18 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 18, 7, 4, 57, 855600, tzinfo=datetime.timezone.utc)),
        ),
    ]
