# Generated by Django 6.0.1 on 2026-03-21 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_date_gameinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 3, 21, 13, 39, 54, 46769, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='image',
            field=models.ImageField(upload_to='media/games/'),
        ),
    ]
