# Generated by Django 6.0.1 on 2026-04-01 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_date_alter_gameinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 4, 1, 14, 25, 50, 371512, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='image',
            field=models.ImageField(upload_to='games/'),
        ),
    ]
